### ISSUE TITLE
Add support for react-navigation-stack@2

### ISSUE THREAD

**Issue by Trashpants** [IjzerenHein/react-navigation-shared-element#16]
So im trying to use this in a new project (used the library totally fine previously) and with the basic code:

```
import { createStackNavigator } from 'react-navigation-stack';
import { createSharedElementStackNavigator } from 'react-navigation-shared-element';
import { OnboardingScreen, LoginScreen } from 'app/src/views/screens';

const GuestNavigator = createSharedElementStackNavigator(
  createStackNavigator,
  {
    Onboard: OnboardingScreen,
    Login: LoginScreen
  },
  {
    initialRouteName: 'Onboard',

    defaultNavigationOptions: {
      cardStyle: { backgroundColor: 'transparent' },
      headerStyle: {
        backgroundColor: 'transparent'
      }
    }
  }
);
export { GuestNavigator };
```

Im using react-navigation ^v4.0.10 and react-navigation-stack ^2.0.12
The app crashes instantly with that code and I get this: 

![IMG_EB9FFB4CA1C2-1](https://user-images.githubusercontent.com/29092604/71928743-0492c280-3190-11ea-91b7-d2f6e197b595.jpeg)

Obviously replace 
```
const GuestNavigator = createSharedElementStackNavigator(
  createStackNavigator,
...
``` 
with
```
const GuestNavigator = createStackNavigator(
...
```
and its totally fine

Being aware that react navigation v5 looks to be completely different am I just SOL right now with this (I've looked at the code and im totally stumped as to how it works - it seems completely black box to me right now, so don't even know how to manually fix this) 

Any help or direction on where to look at fixing this will be greatly appreciated

**Comment by IjzerenHein** [comment]
Hi! There seems to have been a lot of activity on react-navigation-stack in the last couple of days. It seems that the current v2 branch is not compatible at this stage. Could you try using the latest v1 of stack and see whether that fixes the problem?

**Comment by Trashpants** [comment]
Yep v1 works totally fine, looks like this is an issue with switching up to the new version of react-navigation-stack.

**Comment by nandorojo** [comment]
I'm having trouble using this with the `v5` `createNativeStackNavigator` as well. In `react-navigation 5.x`, the `params` prop is moved from `navigation` to `routes` (and from `useNavigation` to the `useRoute` hook).

**Comment by IjzerenHein** [comment]
Yep, v5 is not yet supported. I've begun work on supporting react-navigation-stack@2, but react-navigation@5 is still somewhat further away.

I'm going to close this as the original purpose of this issue was already addressed; and there is already an issue for react-navigation@5.

**Comment by IjzerenHein** [comment]
Support for stack v2 has been officially released.
https://github.com/IjzerenHein/react-navigation-shared-element/releases/tag/v2.0.1

**Comment by TheTimeWalker** [comment]
I had tried the alpha version already but failed to make shared element work at all. The issue persists with v2.0.1

Trying with a minimal configuration, having a SharedStack inside a SwitchNavigation with two screens that have a shared element, there's no movement or anything happening with either an image or text. From debugging it does seems to fetch the next screens `sharedElements` and it does notice screen changes but I still can't make it work.

"react-navigation": "^4.0.10"
"react-navigation-shared-element": "^2.0.1"
"react-navigation-stack": "^2.0.16"

**Comment by IjzerenHein** [comment]
@TheTimeWalker Perhaps it's a problem in combination with the SwitchNavigator. Can you create a new issue and share your minimal config?

**Comment by TheTimeWalker** [comment]
Hey, after taking a small break with this task and later noticing that I accidentally had shared instead of id in `<SharedElement>` since I'm moving away from FluidTransitions :man_facepalming:, I was able to make it work without issues. Sorry about that and thanks for updating this for Stack v2!

**Comment by IjzerenHein** [comment]
No worries, glad it has been resolved 😄👍 
Closing this issue.
